js/adapt-contrib-slider.js, less/slider.less, templates/slider.hbs
- slider scale numbers replace slider handle interaction for accessibility users.
=> onNumberSelected added / template updated

js/adapt-contrib-slider.js
Fixes #56 using code from @oliverfoster old PR that wasn't merged (see old PR) https://github.com/cgkineo/adapt-contrib-slider/commit/006cf23e26714e3e4fc061d608812e085a3915dd
=> Miscalculation in setScore fix

bower.json, package.json, properties.schema
=> Add labelStart, labelEnd to schema

properties.schema
See https://adaptlearning.atlassian.net/browse/ABU-485
=> add _supportedLayout to schema, fixes issues/#58

README.md, example.json, properties.schema
All questions with _attempts value should probably have _shouldDisplayAttempts in the example.json and schema.
=> Abu 644/abu 645

properties.schema
Is _accessibility._ariaLabels.sliderHandle even used?
=> Add globals

js/adapt-contrib-slider.js
https://adaptlearning.atlassian.net/browse/ABU-690
=> Added SCORM interactions support.

templates/slider.hbs
=> a to button

js/adapt-contrib-slider.js
See [ABU-1112](https://adaptlearning.atlassian.net/browse/ABU-1112)
also remove some of the more pointless comments, add where helpful
=> fix for 'sticky handle' in desktop browsers

js/adapt-contrib-slider.js
see [ABU-1139](https://adaptlearning.atlassian.net/browse/ABU-1139)
=> fix for user answer data not being restored properly between sessions

bower.json, js/adapt-contrib-slider.js, properties.schema
This was due to a few issues with  onNumberSelected().
I've also corrected the properties.json for the authoring tool.
=> Fixed #85, styling bug on selecting number

js/adapt-contrib-slider.js
When _correctAnswer was undefined the _correctRange would not work.
This patch fixes the control flow bug to check for undefined or an
empty string.
=> Fixes #90, bug with _correctRange when _correctAnswer is undefined

bower.json, example.json, js/adapt-contrib-slider.js, properties.schema
see https://github.com/adaptlearning/adapt_framework/issues/862
=> adds ability to specify the slider scale 'step'

less/slider.less
removed side spacing to align labels to the right and left edges of the slider
=> issue #1072 #1077

less/slider.less, templates/slider.hbs
updated scale numbers and scale marker to better ahndle larger numbers.
The biggest change is that the marker turned from a circle into a pill.
=> fixes #1054

js/adapt-contrib-slider.js
_isComplete is true when the component was solved before and the course get's relaunched
_isInteractionComplete is true when no more attempts are left or the component gets solved correctly, but get's set to false when course is reloaded
=> use "_isInteractionComplete" instead of "_isComplete"

README.md, bower.json, js/adapt-contrib-slider.js
This allows support for a step interval which isn't a whole number.
=> Adds support for decimal steps

less/slider.less
https://caniuse.com/#search=user-select
=> Fix #1844 IE10/11 user selection bug

js/adapt-contrib-slider.js
when the question is reset - fixes https://github.com/adaptlearning/adapt_framework/issues/1895
=> ensure _isAtLeastOneCorrectSelection is set back to false

js/adapt-contrib-slider.js
Original issue: https://github.com/adaptlearning/adapt_framework/issues/1895.
=> Move resetting of _isAtLeastOneCorrectSelection

js/adapt-contrib-slider.js
This is required in preparation for xAPI compatibility.
=> Added getInteractionObject() function

js/adapt-contrib-slider.js, less/slider.less, properties.schema, templates/slider.hbs
resolves https://github.com/adaptlearning/adapt_framework/issues/2011
=> issue/2011 - New option to hide indicator markers

properties.schema
[#2165](https://github.com/adaptlearning/adapt_framework/issues/2165)
* Made component description easier to digest
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.
=> accessibility: issue/#2165 updated component description

README.md, bower.json, example.json, js/adapt-contrib-slider.js, js/sliderModel.js, js/sliderView.js, less/slider.less, templates/slider.hbs
Narrative converted to use 2 spaces for indentation.
=> update to use 2 spaces for indentation

less/slider.less
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2891
=> Less tidy up

README.md, js/adapt-contrib-slider.js, js/sliderModel.js, js/sliderView.js, properties.schema
... as it's not possible to give a partly-correct answer to this type of question
resolves https://github.com/adaptlearning/adapt_framework/issues/2775
=> remove partly-correct feedback

js/sliderModel.js
Fix to support https://github.com/adaptlearning/adapt-contrib-confidenceSlider/issues/46
=> Fix for default item selection

js/sliderModel.js, properties.schema
part of adaptlearning/adapt_framework#2942
=> add support for correct/user answer text for screenreaders

bower.json, js/adapt-contrib-slider.js, js/sliderModel.js, js/sliderView.js
ES6 code conversion was completed in https://github.com/LearningPool/adapt-contrib-slider/pull/3
The purpose of this PR is to add in the imports/exports to the component.
https://github.com/adaptlearning/adapt_framework/issues/2808
=> 2808 - added imports/exports to Slider

js/adapt-contrib-slider.js
requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799
* Switched to components.register from Adapt.register
=> issue/2799 Removed redundant behaviour

less/rangeslider.less
Fixes: #165 
* Converted `:focus` to `:focus-visible`
=> Update: Convert focus to focus-visible (fixes #165)

example.json, properties.schema, schema/component.schema.json
#167 
* default instruction text provided
=> New: Provide default instruction text (fixes #167)

test/e2e/slider.cy.js
=> Chore: e2e tests on slider component (Issue/201)

test/e2e/slider.cy.js
=> Fix: Moved striphtml function outside loop (fixes #206)

templates/slider.jsx
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
#209 
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* role added to component__widget div (fixes #209)
References:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role
- https://github.com/adaptlearning/adapt-contrib-mcq/blob/652de564338f5e0a2181d3f5f51c17d111cae998/templates/mcq.jsx#L40
=> Fix: role added to component__widget div (fixes #209)
